import { v4 as uuid } from "uuid";

export const recipes = [
  {
    id: uuid(),
    image: "https://picsum.photos/208/320?random=1",
    name: "Spaghetti Carbonara",
    cuisine: "Italian",
    ingredients: [
      "200g spaghetti",
      "150g pancetta",
      "2 cloves garlic minced",
      "2 large eggs",
      "50g grated Parmesan cheese",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cook the spaghetti according to package instructions. Drain and set aside.",
      "In a large skillet, cook the pancetta over medium heat until crispy. Remove from the skillet and set aside, leaving the rendered fat in the skillet.",
      "In the same skillet, add the minced garlic and cook for a minute until fragrant.",
      "In a bowl, whisk together the eggs and grated Parmesan cheese. Season with salt and pepper.",
      "Add the cooked spaghetti to the skillet with the garlic and toss to coat with the rendered fat.",
      "Remove the skillet from heat and quickly add the egg mixture, stirring constantly to coat the pasta. The residual heat will cook the eggs and create a creamy sauce.",
      "Crumble the cooked pancetta and sprinkle it over the pasta. Toss again to combine.",
      "Serve the spaghetti carbonara hot, garnished with additional grated Parmesan cheese.",
    ],
  },
  {
    id: uuid(),
    image: "https://picsum.photos/208/320?random=2",
    name: "Chicken Tikka Masala",
    cuisine: "Indian",
    ingredients: [
      "500g boneless chicken, cut into cubes",
      "1 cup plain yogurt",
      "2 tablespoons lemon juice",
      "2 teaspoons ground cumin",
      "2 teaspoons ground paprika",
      "1 teaspoon ground turmeric",
      "1 teaspoon ground coriander",
      "1 teaspoon garam masala",
      "1 teaspoon chili powder",
      "2 cloves garlic, minced",
      "1-inch piece of ginger, grated",
      "1 cup tomato puree",
      "1 cup heavy cream",
      "Salt to taste",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "In a bowl, combine the yogurt, lemon juice, ground cumin, paprika, turmeric, coriander, garam masala, chili powder, minced garlic, and grated ginger. Mix well.",
      "Add the chicken cubes to the marinade and toss to coat. Cover and refrigerate for at least 1 hour, or overnight for best results.",
      "Preheat the grill or preheat the oven to 400°F (200°C).",
      "Thread the marinated chicken cubes onto skewers and grill them for 10-12 minutes, turning occasionally, until cooked through and slightly charred. If using the oven, arrange the chicken on a baking sheet and bake for 15-20 minutes.",
      "In a large skillet, heat a tablespoon of oil over medium heat. Add the tomato puree and cook for a few minutes until it thickens slightly.",
      "Stir in the heavy cream and season with salt. Simmer the sauce for 5-10 minutes.",
      "Add the grilled chicken to the skillet and simmer for another 5 minutes, allowing the flavors to meld together.",
      "Garnish the chicken tikka masala with fresh cilantro and serve hot with naan bread or steamed rice.",
    ],
  },
  {
    id: uuid(),
    image: "https://picsum.photos/208/320?random=3",
    name: "Caesar Salad",
    cuisine: "American",
    ingredients: [
      "1 head romaine lettuce, chopped",
      "1 cup croutons",
      "1/4 cup grated Parmesan cheese",
      "2 tablespoons lemon juice",
      "1 clove garlic, minced",
      "2 anchovy fillets, minced (optional)",
      "1/2 cup mayonnaise",
      "1/4 cup grated Parmesan cheese",
      "2 tablespoons olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine the chopped romaine lettuce, croutons, and grated Parmesan cheese.",
      "In a separate small bowl, whisk together the lemon juice, minced garlic, minced anchovy fillets (if using), mayonnaise, grated Parmesan cheese, olive oil, salt, and pepper to make the dressing.",
      "Pour the dressing over the salad and toss to coat evenly.",
      "Serve the Caesar salad as a side dish or add grilled chicken or shrimp to make it a complete meal.",
    ],
  },
  {
    id: uuid(),
    image: "https://picsum.photos/208/320?random=4",
    name: "Sushi Rolls",
    cuisine: "Japanese",
    ingredients: [
      "4 cups sushi rice",
      "4 sheets nori (seaweed)",
      "Assorted fillings (e.g., cucumber, avocado, cooked shrimp, smoked salmon)",
      "Soy sauce for dipping",
      "Wasabi and pickled ginger for serving",
    ],
    instructions: [
      "Prepare the sushi rice according to package instructions and let it cool.",
      "Place a sheet of nori on a bamboo sushi mat or a clean kitchen towel.",
      "Moisten your hands with water and take a handful of sushi rice, gently pressing it onto the nori to cover about 3/4 of the sheet.",
      "Arrange your desired fillings in a line across the center of the rice.",
      "Using the mat or towel, roll the nori tightly over the fillings, applying gentle pressure to ensure a firm roll.",
      "Repeat the process with the remaining nori sheets and fillings.",
      "Use a sharp knife to slice each sushi roll into bite-sized pieces.",
      "Serve the sushi rolls with soy sauce, wasabi, and pickled ginger.",
    ],
  },
  {
    id: uuid(),
    image: "https://picsum.photos/208/320?random=5",
    name: "Tacos al Pastor",
    cuisine: "Mexican",
    ingredients: [
      "500g pork shoulder, thinly sliced",
      "1 cup pineapple juice",
      "3 tablespoons achiote paste",
      "2 tablespoons white vinegar",
      "2 cloves garlic, minced",
      "1 teaspoon dried oregano",
      "1 teaspoon ground cumin",
      "1 teaspoon smoked paprika",
      "1/2 teaspoon chili powder",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Corn tortillas",
      "Chopped onions, cilantro, and pineapple for garnish",
    ],
    instructions: [
      "In a bowl, combine the pineapple juice, achiote paste, white vinegar, minced garlic, dried oregano, ground cumin, smoked paprika, chili powder, salt, and black pepper to make the marinade.",
      "Add the thinly sliced pork shoulder to the marinade and toss to coat. Cover and refrigerate for at least 2 hours, or overnight for best results.",
      "Preheat a grill or a grill pan over medium-high heat.",
      "Remove the marinated pork from the fridge and thread the slices onto skewers. Discard any excess marinade.",
      "Grill the pork skewers for 5-7 minutes on each side, or until cooked through and slightly charred.",
      "Remove the pork from the skewers and let it rest for a few minutes before slicing it into smaller pieces.",
      "Warm the corn tortillas on the grill or in a dry skillet.",
      "Assemble the tacos al pastor by placing some sliced pork onto each tortilla. Top with chopped onions, cilantro, and pineapple.",
      "Serve the tacos al pastor hot, and enjoy the flavors of Mexico!",
    ],
  },
];
